FROM openjdk:8u151-jdk

# Set the working directory to /app
WORKDIR /app

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the jar when the container launches
CMD ["java", "-jar", "target/lsd-app-1.0-SNAPSHOT-jar-with-dependencies.jar"]